name: DeployStagingi18n

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy to www.${{ matrix.language }}.orchid.dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['ja', 'ko', 'zh']

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Configure Git Credentials
      run: |
        mkdir -p $XDG_CONFIG_HOME/git
        echo "https://${{ secrets.CODECOMMIT_GIT_USERNAME }}:${{ secrets.CODECOMMIT_GIT_PASSWORD }}@git-codecommit.us-west-2.amazonaws.com/v1/repos/${{ matrix.language }}.orchid.dev/" >> $XDG_CONFIG_HOME/git/credentials
        git config --global credential.helper store
    - name: Deploy to www.${{ matrix.language }}.orchid.dev
      run: |
        git config --global 'url.https://git-codecommit.us-west-2.amazonaws.com/v1/repos/${{ matrix.language }}.orchid.dev/.insteadOf' 'ssh://git-codecommit.us-west-2.amazonaws.com/v1/repos/${{ matrix.language }}.orchid.dev'
        ./deploy.sh staging ${{ matrix.language }}
